"""A fixed deck, used by /api/sample-deck.

The browser suites run against this rather than a live model: it needs no API
key, never changes, and exercises every phase including a proper ATOMIC
bedrock below the deepest descent step.
"""

SAMPLE_DECK = {
    "topic": "Why the sky is blue",
    "question": "Why does the daytime sky appear blue rather than any other colour?",
    "followups": [
        "Why is a sunset red if the same air is doing the scattering?",
        "What colour is the sky on a planet with no atmosphere?",
        "Why is the sea blue — is it the same reason?",
    ],
    "cards": [
        {
            "phase": "question",
            "level": 0,
            "title": "The Sky Is Blue",
            "question": "What do we actually start out believing here?",
            "tag": "ASSUMPTION",
            "principle": "The sky is a blue thing that we look at.",
            "chain": [],
            "discarded": [
                "The sky is a surface with a colour",
                "The sky reflects the ocean",
            ],
            "explanation": "Ordinary speech treats the sky as an object that owns a colour. Nothing has been proven yet. Before decomposing, note that 'the sky' is not a material object at all — it is a direction you look in.",
            "takeaway": "The starting belief names an object that does not exist.",
        },
        {
            "phase": "descent",
            "level": 1,
            "title": "Colour Is Light Reaching An Eye",
            "question": "What is a perceived colour made of?",
            "tag": "VERIFIED",
            "principle": "Seeing a colour means light of certain wavelengths arrives at the retina.",
            "chain": ["The sky looks blue", "Blue light arrives from that direction"],
            "discarded": [],
            "explanation": "No colour exists in the air itself. What can be measured is light travelling from a direction into an eye. So the question becomes: why does light from empty directions reach us at all?",
            "takeaway": "Ask what arrives, not what the thing is.",
        },
        {
            "phase": "descent",
            "level": 2,
            "title": "Air Redirects Light",
            "question": "Why does light arrive from a direction with no source in it?",
            "tag": "VERIFIED",
            "principle": "Gas molecules redirect passing electromagnetic waves in all directions.",
            "chain": [
                "The sky looks blue",
                "Blue light arrives from that direction",
                "Air redirects light toward us",
            ],
            "discarded": [],
            "explanation": "The Sun sits in one small part of the sky, yet light comes from everywhere. Something between the Sun and the eye must be redirecting it. Measurement shows the atmosphere's gas molecules do this.",
            "takeaway": "Empty-looking sky is full of redirected light.",
        },
        {
            "phase": "descent",
            "level": 3,
            "title": "Redirection Depends On Wavelength",
            "question": "Why is the redirected light not white?",
            "tag": "VERIFIED",
            "principle": "Scattering by particles far smaller than the wavelength grows sharply as wavelength shortens.",
            "chain": [
                "The sky looks blue",
                "Blue light arrives from that direction",
                "Air redirects light toward us",
                "Short wavelengths redirect far more",
            ],
            "discarded": ["Sunlight is 'white' and therefore colourless"],
            "explanation": "Sunlight contains many wavelengths together. Air molecules are much smaller than those wavelengths, and in that regime the redirection strength rises steeply as wavelength falls. Short waves are redirected many times more than long ones.",
            "takeaway": "Short waves scatter, long waves pass through.",
        },
        {
            "phase": "bedrock",
            "level": 4,
            "title": "Charges Radiate When Driven",
            "question": "Why should a small molecule redirect short waves more at all?",
            "tag": "ATOMIC",
            "principle": "An accelerating electric charge radiates, and radiated power rises with the square of the driving frequency.",
            "chain": [
                "The sky looks blue",
                "Blue light arrives from that direction",
                "Air redirects light toward us",
                "Short wavelengths redirect far more",
                "Driven charges radiate, harder at high frequency",
            ],
            "discarded": [],
            "explanation": "A passing wave drives the charges in a molecule back and forth. Driven charges accelerate, and accelerating charges radiate a new wave in all directions. Higher frequency means harder acceleration, so more radiated power. This is electromagnetism itself — it does not reduce further.",
            "takeaway": "Bedrock: driven charge radiates, harder at higher frequency.",
        },
        {
            "phase": "rebuild",
            "level": 2,
            "title": "Rebuild: The Sky From Bedrock",
            "question": "Can the whole effect be rebuilt from that alone?",
            "tag": "VERIFIED",
            "principle": "Sunlight drives atmospheric charges, which re-radiate short wavelengths preferentially in every direction.",
            "chain": [
                "Driven charge radiates, harder at high frequency",
                "Air re-radiates short waves in all directions",
                "Every direction glows with short-wavelength light",
            ],
            "discarded": [],
            "explanation": "Sunlight of many wavelengths enters the air. Each molecule's charges are driven and re-radiate, most strongly at the short-wave end. That re-radiated light leaves in every direction, so every line of sight glows — including ones pointing nowhere near the Sun.",
            "takeaway": "No surface needed. The air itself glows.",
        },
        {
            "phase": "insight",
            "level": 0,
            "title": "Why Blue And Not Violet",
            "question": "What does this reveal that the surface story hides?",
            "tag": "VERIFIED",
            "principle": "The perceived colour is set jointly by the physics of scattering and the response of the eye.",
            "chain": [],
            "discarded": ["The sky 'is' blue"],
            "explanation": "Violet scatters even more strongly than blue, so pure physics predicts a violet sky. Sunlight contains less violet, more is absorbed high up, and human cones respond weakly to it. The answer is not a property of the sky — it is a property of light and observer together.",
            "takeaway": "Remove the observer and the question loses its answer.",
        },
    ],
}
